######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 14 13:50:32 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . DigitStopWatch
INCLUDEPATH += . DigitStopWatch

# Input
HEADERS += Main.h sysapi.h DigitStopWatch/pQDigitStopWatch.h
SOURCES += linuxapi.cpp Main.cpp DigitStopWatch/pQDigitStopWatch.cpp
